Algoritmo "Exercício Soma"
// 
//  
// Descrição   : Exercício Estrutura Sequencial
// Autor(a)    : Cleiber Dorneles
// Data atual  : 04/06/2026
Var
// Seção de Declarações das variáveis 
    x, y, soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Insira o Primeiro valor:")
   leia(x)
   escreval("Insira o Segundo valor:")
   leia(y)
   soma <- x+y
   escreval("A Soma dos valores é:" ,soma)
Fimalgoritmo