Algoritmo "Exercício Círculo"
// 
//  
// Descrição   : Exercício Estrutura Sequencial
// Autor(a)    : Cleiber Dorneles
// Data atual  : 04/06/2026
Var
// Seção de Declarações das variáveis 
    raio, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Insira o Raio do círculo:")
   leia(raio)
   area <- 3.14*(raio^2)
   escreval("A área do círculo é de:" ,area)
Fimalgoritmo